#!/bin/sh

if [ -z $1 ]; then
	echo "repo path is missing"
	exit
fi

if [ -z $2 ]; then
	echo "image name is missing"
	exit
fi

repo="https://github.com/$1/tarball/master"
image=$2
dir=dl

# Download repo
rm -rf $dir
mkdir dl
curl -L $repo | tar xz -C $dir --strip-components 1

# Build and push image
cd $dir
docker build -t $image .
docker login
docker push "$image:latest"
