version: "3"

services:
  backend:
    build:
      context: ../../material-applications/example-backend/
      dockerfile: ../../part2/2.10/backend.Dockerfile
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    ports:
      - "8080"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ../../material-applications/example-frontend/
      dockerfile: ../../part2/2.10/frontend.Dockerfile
    ports:
      - "5000"

  redis:
    image: redis
    ports:
      - "6379"

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"

  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
