version: "3"

services:
  backend:
    build:
      context: ../../material-applications/example-backend/
      dockerfile: ../../part1/1.14/backend.Dockerfile
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ../../material-applications/example-frontend/
      dockerfile: ../../part1/1.14/frontend.Dockerfile
    ports:
      - "5000:5000"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
